print("\033[0;37;44m Black        ###")
print("            ###  #     ")
print("           #   #  #   ")
print("          #     #### ")
print("          #     #   #  ")
print("         #       ## #  ")
print("       ###          #  ")
print("     ##  #     ## # #  ")
print("    #     #    ## # #   ####")
print("   #      #         ####    ##")
print("   #    #  #  #### ##  #    # #")
print("   #   # #  #     #    #    # #")
print("    #  #  #  #####     #   ###")
print("     #    #       ##### ####")
print("      #  #       #    ")
print("       ##       #      ")
print("       #        #      ")
print("       #        #      ")
print("      #          #     ")
print("     #     ##     #   ")
print("   ##     #  #    #   ")
print(" ##      #   #   ###")
print("#       #   #       #")
print("#########   ######### ")      
